//! `AlignmentMode::HeaderColumn` was `RowKey { columns: vec![1] }` under another name (M10 unit 06).
//!
//! `header_column_alignment` delegated to `row_key_alignment` with `columns = [1]` and never read a
//! header; there is no column alignment anywhere in this crate. The mode is removed, and this file is
//! the migration's proof: on five comparisons where alignment changes the outcome, **`RowKey` on column 1
//! produces what `HeaderColumn` produced** -- exactly, on four; the fifth moved when f130 fixed a defect
//! both modes shared (a row with no key was never compared), and its entry in `BASELINE` says so.
//!
//! `HeaderColumn` no longer exists, so the "before" side is recorded. `BASELINE` was generated by running
//! **both** modes on the pre-removal tree (`HEAD` at the start of the unit), asserting they agreed, and printing
//! the fingerprint of the `HeaderColumn` run — every observable of the result: the summary, the alignment
//! summary, every cell diff with its address and values, and every sheet diagnostic with its location. The
//! review request's `evidence/01-…` is that run. This test then holds `RowKey { columns: vec![1] }` to it.

mod support;
use support::{wb_sheets, wb_strings};

use sheets_diff::options::AlignmentMode;
use sheets_diff::{DiffOptions, WorkbookDiff, compare_bytes_with_options};

/// Everything a caller can observe about how alignment changed the outcome, in one comparable string.
fn fingerprint(d: &WorkbookDiff) -> String {
    let mut out = format!(
        "sum:{}/{}/{}/{}|",
        d.summary.cells_changed,
        d.summary.values_changed,
        d.summary.formulas_changed,
        d.metrics.cells_compared
    );
    for s in &d.sheets {
        out += &format!("[{:?}", s.change);
        if let Some(a) = &s.alignment_summary {
            out += &format!(
                " al:{}/{}/{}/{:?}",
                a.matched_rows, a.inserted_rows, a.removed_rows, a.confidence
            );
        }
        for c in &s.cell_diffs {
            out += &format!(
                " {}:{:?}",
                c.address.a1,
                c.value
                    .as_ref()
                    .map(|v| (v.old.display_string(), v.new.display_string()))
            );
        }
        for x in &s.diagnostics {
            out += &format!(
                " !{}@{:?}/{:?}",
                x.kind.code(),
                x.location.sheet_order,
                x.location.sheet_name
            );
        }
        out += "]";
    }
    out
}

fn row_key_1() -> DiffOptions {
    DiffOptions::builder()
        .alignment(AlignmentMode::RowKey { columns: vec![1] })
        .build()
        .unwrap()
}

fn fixture(n: &str) -> (Vec<u8>, Vec<u8>) {
    let d = std::path::Path::new("tests/fixtures/generated").join(n);
    (
        std::fs::read(d.join("old.xlsx")).unwrap(),
        std::fs::read(d.join("new.xlsx")).unwrap(),
    )
}

fn cases() -> Vec<(&'static str, Vec<u8>, Vec<u8>)> {
    let mut v = vec![];
    let (o, n) = fixture("alignment_header_column");
    v.push(("fixture alignment_header_column", o, n));
    let (o, n) = fixture("row_insertion_cascade");
    v.push(("fixture row_insertion_cascade", o, n));
    let (o, n) = fixture("alignment_row_signature");
    v.push(("fixture alignment_row_signature", o, n));
    v.push((
        "duplicate keys in the header column",
        wb_strings(&[
            (0, 0, "h"),
            (0, 1, "v"),
            (1, 0, "dup"),
            (1, 1, "a"),
            (2, 0, "dup"),
            (2, 1, "b"),
            (3, 0, "u"),
            (3, 1, "c"),
        ]),
        wb_strings(&[
            (0, 0, "h"),
            (0, 1, "v"),
            (1, 0, "dup"),
            (1, 1, "a"),
            (2, 0, "u"),
            (2, 1, "c"),
        ]),
    ));
    let a: &[(u32, u16, &str)] = &[
        (0, 0, "id"),
        (0, 1, "x"),
        (1, 0, "k1"),
        (1, 1, "1"),
        (2, 0, "k2"),
        (2, 1, "2"),
    ];
    let b: &[(u32, u16, &str)] = &[
        (0, 0, "id"),
        (0, 1, "x"),
        (1, 0, "k0"),
        (1, 1, "9"),
        (2, 0, "k1"),
        (2, 1, "1"),
        (3, 0, "k2"),
        (4, 1, "3"),
    ];
    v.push((
        "renamed and moved sheet",
        wb_sheets(&[("Old", a), ("Stay", &[])]),
        wb_sheets(&[("Stay", &[]), ("New", b)]),
    ));
    v
}

/// What `HeaderColumn` produced on each case, recorded on the pre-removal tree.
const BASELINE: &[(&str, &str)] = &[
    (
        "fixture alignment_header_column",
        r#"sum:2/2/0/10|[Modified al:4/1/0/High A2:Some(("", "id_inserted")) B2:Some(("", "val_inserted"))]"#,
    ),
    (
        "fixture row_insertion_cascade",
        r#"sum:2/2/0/42|[Modified al:20/1/0/High A1:Some(("", "id_inserted")) B1:Some(("", "val_inserted"))]"#,
    ),
    (
        "fixture alignment_row_signature",
        r#"sum:2/2/0/12|[Modified al:5/1/0/High A1:Some(("", "inserted_a")) B1:Some(("", "inserted_b"))]"#,
    ),
    (
        "duplicate keys in the header column",
        r#"sum:2/2/0/8|[Modified al:3/0/1/High A3:Some(("dup", "")) B3:Some(("b", "")) !duplicate_alignment_key@Some(0)/Some("Sheet1")]"#,
    ),
    // Moved by f130 (3.1.0), and the only entry that is. This case's new sheet has a row with no
    // key -- `B5 = "3"`, nothing in `A5` -- and both modes through 3.0.0 never compared it: the
    // recorded `HeaderColumn` output was
    //   sum:3/3/0/8|[RenamedAndMoved { confidence: Low, reason: SoleRemainingPair } al:3/1/0/High
    //   A2:Some(("", "k0")) B2:Some(("", "9")) B3:Some(("2", ""))][Moved al:0/0/0/Exact]
    // which omits `B5` (a missed difference) and calls the alignment `High` with no warning.
    // `RowKey` now reports `B5`, warns, and says `Medium`; the four other entries -- every row keyed --
    // are untouched. A migrated `HeaderColumn` caller gets the fix with `RowKey`.
    (
        "renamed and moved sheet",
        r#"sum:4/4/0/9|[RenamedAndMoved { confidence: Low, reason: SoleRemainingPair } al:3/2/0/Medium A2:Some(("", "k0")) B2:Some(("", "9")) B3:Some(("2", "")) B5:Some(("", "3")) !missing_alignment_key@Some(1)/Some("New")][Moved al:0/0/0/Exact]"#,
    ),
];

#[test]
fn row_key_on_column_1_produces_what_header_column_produced() {
    let cases = cases();
    assert_eq!(cases.len(), BASELINE.len());
    for ((label, old, new), (blabel, baseline)) in cases.iter().zip(BASELINE) {
        assert_eq!(label, blabel);
        let got = fingerprint(&compare_bytes_with_options(old, new, row_key_1()).unwrap());
        assert_eq!(
            &got, baseline,
            "`{label}`: RowKey{{[1]}} no longer matches what HeaderColumn produced"
        );
    }
}

/// The control: on every case alignment changes the outcome, so equality is between two *aligned*
/// results and not between two defaults.
#[test]
fn on_each_case_alignment_changes_the_outcome() {
    for (label, old, new) in cases() {
        let aligned = fingerprint(&compare_bytes_with_options(&old, &new, row_key_1()).unwrap());
        let positional =
            fingerprint(&compare_bytes_with_options(&old, &new, DiffOptions::default()).unwrap());
        assert_ne!(
            aligned, positional,
            "`{label}`: alignment did nothing, so the equality proves nothing"
        );
    }
}
